### PR TITLE
Update ConsumerProfile.swift

### PR DESCRIPTION
**Pull request by eurecho**
changed the buyerMenu to  buyer_Menu please check if the code will have no erorrs

### CODE REVIEW

**Review by 2225962 — COMMENTED** [review]
The code has been reviewed and ready to submit

**Comment by RhyenSftwareEngr** [comment]
On It

**Review by RhyenSftwareEngr — CHANGES_REQUESTED** [review]
It seems that you must also change the method name buyer_menu in main.swift line#75

**Comment by RhyenSftwareEngr** [comment]
@AVILLANOZA can you suggest anything in ConsumerProfile.swift?

**Comment by RhyenSftwareEngr** [comment]
I will already merge it to main branch, and if i there are other concerns, I already mentioned one of my teammate to triple check for code concerns

**Pull request merged**
